### PR TITLE
Add `automountServiceAccountToken` to `ServiceAccount`

### PR DESCRIPTION
**Pull request by SakulK**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#opt-out-of-api-credential-automounting

### CODE REVIEW

**Comment by hagay3** [comment]
@SakulK 
Thank you for opening the PR and contributing to skuber!
I think it's a good opportunity to add integration tests to `ServiceAccount`, wdyt?

e.g:
https://github.com/hagay3/skuber/blob/master/client/src/it/scala/skuber/ServiceSpec.scala

**Comment by SakulK** [comment]
@hagay3 
Sure, I created a basic test suite based on the `ServiceSpec` plus an additional case for `automountServiceAccountToken`, let me know if it's good enough :slightly_smiling_face:

**Comment by hagay3** [comment]
@SakulK 
Fantastic work! I will create a new release shortly.

**Comment by hagay3** [comment]
@SakulK 
v3.0.4 released
https://github.com/hagay3/skuber/releases/tag/v3.0.4

**Pull request merged**
